---
- name: Remove all new app nodes from registered_nodes
  set_fact:
    registered_nodes: '{{ registered_nodes | difference([ node ]) }}'
  when:
    - '("app" in groups) and (groups["app"] | list != new_app_nodes | list)'
    - 'node["name"] in new_app_nodes'
